export const SEARCH_BOX_POST_QUERY = 'SEARCH_BOX_POST_QUERY';
export const SEARCH_BOX_POST_QUERY_SUCCESS = 'SEARCH_BOX_POST_QUERY_SUCCESS';
export const SEARCH_BOX_POST_QUERY_FAILURE = 'SEARCH_BOX_POST_QUERY_FAILURE';